server:
  port: 8081

Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wj?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: admin
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    connect-timeout: 2000
